apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: kube-system
spec:
  targetNamespace: loki
  chart: https://grafana.github.io/loki/charts/loki-stack-2.1.2.tgz
