---
name: Traefik-v2-loadbalancer
title: Traefik v2 (LoadBalancer)
version: "2.5"
default: false
maintainer: "johannes@jitesoft.com, saiyam@imaginekube.com"
description: An open source Edge Router working as an ingress controller and load balancer inside your kubernetes cluster.
url: https://traefik.io
category: architecture
required_services:
  - loadbalancer
