global:
  ingress:
    enabled: true
    class: traefik
prometheus:
  install: false
certmanager:
  install: false
nginx-ingress:
  enabled: false
gitlab:
  gitaly:
    persistence:
      storageClass: imaginekube-volume
      size: 50Gi
postgresql:
  persistence:
    storageClass: imaginekube-volume
    size: 8Gi
minio:
  persistence:
    storageClass: imaginekube-volume
    size: 10Gi
redis:
  master:
    persistence:
      storageClass: imaginekube-volume
      size: 5Gi

